/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKLOGIC_H
#define _MOCKLOGIC_H

#include "unity.h"
#include "logic.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mocklogic_Init(void);
void Mocklogic_Destroy(void);
void Mocklogic_Verify(void);




#define logic_create_report_ExpectAnyArgs() TEST_FAIL_MESSAGE("logic_create_report requires _ExpectAnyArgsAndReturn");
#define logic_create_report_ExpectAnyArgsAndReturn(cmock_retval) logic_create_report_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void logic_create_report_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, cJSON* cmock_to_return);
#define logic_create_report_Expect(title, description, date) TEST_FAIL_MESSAGE("logic_create_report requires _ExpectAndReturn");
#define logic_create_report_ExpectAndReturn(title, description, date, cmock_retval) logic_create_report_CMockExpectAndReturn(__LINE__, title, description, date, cmock_retval)
void logic_create_report_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* title, const char* description, const char* date, cJSON* cmock_to_return);
typedef cJSON* (* CMOCK_logic_create_report_CALLBACK)(const char* title, const char* description, const char* date, int cmock_num_calls);
void logic_create_report_AddCallback(CMOCK_logic_create_report_CALLBACK Callback);
void logic_create_report_Stub(CMOCK_logic_create_report_CALLBACK Callback);
#define logic_create_report_StubWithCallback logic_create_report_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
