/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocklogic.h"

static const char* CMockString_date = "date";
static const char* CMockString_description = "description";
static const char* CMockString_logic_create_report = "logic_create_report";
static const char* CMockString_title = "title";

typedef struct _CMOCK_logic_create_report_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  cJSON* ReturnVal;
  const char* Expected_title;
  const char* Expected_description;
  const char* Expected_date;

} CMOCK_logic_create_report_CALL_INSTANCE;

static struct MocklogicInstance
{
  char logic_create_report_CallbackBool;
  CMOCK_logic_create_report_CALLBACK logic_create_report_CallbackFunctionPointer;
  int logic_create_report_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE logic_create_report_CallInstance;
} Mock;


void Mocklogic_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.logic_create_report_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_logic_create_report);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.logic_create_report_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mocklogic_Init(void)
{
  Mocklogic_Destroy();
}

void Mocklogic_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

cJSON* logic_create_report(const char* title, const char* description, const char* date)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_logic_create_report_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_logic_create_report);
  cmock_call_instance = (CMOCK_logic_create_report_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.logic_create_report_CallInstance);
  Mock.logic_create_report_CallInstance = CMock_Guts_MemNext(Mock.logic_create_report_CallInstance);
  if (!Mock.logic_create_report_CallbackBool &&
      Mock.logic_create_report_CallbackFunctionPointer != NULL)
  {
    cJSON* cmock_cb_ret = Mock.logic_create_report_CallbackFunctionPointer(title, description, date, Mock.logic_create_report_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_logic_create_report,CMockString_title);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_title, title, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_logic_create_report,CMockString_description);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_description, description, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_logic_create_report,CMockString_date);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_date, date, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.logic_create_report_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.logic_create_report_CallbackFunctionPointer(title, description, date, Mock.logic_create_report_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_logic_create_report(CMOCK_logic_create_report_CALL_INSTANCE* cmock_call_instance, const char* title, const char* description, const char* date);
void CMockExpectParameters_logic_create_report(CMOCK_logic_create_report_CALL_INSTANCE* cmock_call_instance, const char* title, const char* description, const char* date)
{
  cmock_call_instance->Expected_title = title;
  cmock_call_instance->Expected_description = description;
  cmock_call_instance->Expected_date = date;
}

void logic_create_report_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, cJSON* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_logic_create_report_CALL_INSTANCE));
  CMOCK_logic_create_report_CALL_INSTANCE* cmock_call_instance = (CMOCK_logic_create_report_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.logic_create_report_CallInstance = CMock_Guts_MemChain(Mock.logic_create_report_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void logic_create_report_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* title, const char* description, const char* date, cJSON* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_logic_create_report_CALL_INSTANCE));
  CMOCK_logic_create_report_CALL_INSTANCE* cmock_call_instance = (CMOCK_logic_create_report_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.logic_create_report_CallInstance = CMock_Guts_MemChain(Mock.logic_create_report_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_logic_create_report(cmock_call_instance, title, description, date);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void logic_create_report_AddCallback(CMOCK_logic_create_report_CALLBACK Callback)
{
  Mock.logic_create_report_CallbackBool = (char)1;
  Mock.logic_create_report_CallbackFunctionPointer = Callback;
}

void logic_create_report_Stub(CMOCK_logic_create_report_CALLBACK Callback)
{
  Mock.logic_create_report_CallbackBool = (char)0;
  Mock.logic_create_report_CallbackFunctionPointer = Callback;
}

