/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKPRESENTATION_H
#define _MOCKPRESENTATION_H

#include "unity.h"
#include "presentation.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockpresentation_Init(void);
void Mockpresentation_Destroy(void);
void Mockpresentation_Verify(void);




#define presentation_collect_and_save_report_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("presentation_collect_and_save_report requires _Expect (not AndReturn)");
#define presentation_collect_and_save_report_Expect() presentation_collect_and_save_report_CMockExpect(__LINE__)
void presentation_collect_and_save_report_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_presentation_collect_and_save_report_CALLBACK)(int cmock_num_calls);
void presentation_collect_and_save_report_AddCallback(CMOCK_presentation_collect_and_save_report_CALLBACK Callback);
void presentation_collect_and_save_report_Stub(CMOCK_presentation_collect_and_save_report_CALLBACK Callback);
#define presentation_collect_and_save_report_StubWithCallback presentation_collect_and_save_report_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
