/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockdata.h"

static const char* CMockString_data_load_reports = "data_load_reports";
static const char* CMockString_data_save_report = "data_save_report";
static const char* CMockString_report = "report";

typedef struct _CMOCK_data_save_report_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  cJSON* Expected_report;

} CMOCK_data_save_report_CALL_INSTANCE;

typedef struct _CMOCK_data_load_reports_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  cJSON* ReturnVal;

} CMOCK_data_load_reports_CALL_INSTANCE;

static struct MockdataInstance
{
  char data_save_report_CallbackBool;
  CMOCK_data_save_report_CALLBACK data_save_report_CallbackFunctionPointer;
  int data_save_report_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE data_save_report_CallInstance;
  char data_load_reports_CallbackBool;
  CMOCK_data_load_reports_CALLBACK data_load_reports_CallbackFunctionPointer;
  int data_load_reports_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE data_load_reports_CallInstance;
} Mock;


void Mockdata_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.data_save_report_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_data_save_report);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.data_save_report_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.data_load_reports_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_data_load_reports);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.data_load_reports_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockdata_Init(void)
{
  Mockdata_Destroy();
}

void Mockdata_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int data_save_report(cJSON* report)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_data_save_report_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_data_save_report);
  cmock_call_instance = (CMOCK_data_save_report_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.data_save_report_CallInstance);
  Mock.data_save_report_CallInstance = CMock_Guts_MemNext(Mock.data_save_report_CallInstance);
  if (!Mock.data_save_report_CallbackBool &&
      Mock.data_save_report_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.data_save_report_CallbackFunctionPointer(report, Mock.data_save_report_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_data_save_report,CMockString_report);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_report), (void*)(report), sizeof(cJSON), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.data_save_report_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.data_save_report_CallbackFunctionPointer(report, Mock.data_save_report_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_data_save_report(CMOCK_data_save_report_CALL_INSTANCE* cmock_call_instance, cJSON* report);
void CMockExpectParameters_data_save_report(CMOCK_data_save_report_CALL_INSTANCE* cmock_call_instance, cJSON* report)
{
  cmock_call_instance->Expected_report = report;
}

void data_save_report_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_data_save_report_CALL_INSTANCE));
  CMOCK_data_save_report_CALL_INSTANCE* cmock_call_instance = (CMOCK_data_save_report_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.data_save_report_CallInstance = CMock_Guts_MemChain(Mock.data_save_report_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void data_save_report_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cJSON* report, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_data_save_report_CALL_INSTANCE));
  CMOCK_data_save_report_CALL_INSTANCE* cmock_call_instance = (CMOCK_data_save_report_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.data_save_report_CallInstance = CMock_Guts_MemChain(Mock.data_save_report_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_data_save_report(cmock_call_instance, report);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void data_save_report_AddCallback(CMOCK_data_save_report_CALLBACK Callback)
{
  Mock.data_save_report_CallbackBool = (char)1;
  Mock.data_save_report_CallbackFunctionPointer = Callback;
}

void data_save_report_Stub(CMOCK_data_save_report_CALLBACK Callback)
{
  Mock.data_save_report_CallbackBool = (char)0;
  Mock.data_save_report_CallbackFunctionPointer = Callback;
}

cJSON* data_load_reports(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_data_load_reports_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_data_load_reports);
  cmock_call_instance = (CMOCK_data_load_reports_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.data_load_reports_CallInstance);
  Mock.data_load_reports_CallInstance = CMock_Guts_MemNext(Mock.data_load_reports_CallInstance);
  if (!Mock.data_load_reports_CallbackBool &&
      Mock.data_load_reports_CallbackFunctionPointer != NULL)
  {
    cJSON* cmock_cb_ret = Mock.data_load_reports_CallbackFunctionPointer(Mock.data_load_reports_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.data_load_reports_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.data_load_reports_CallbackFunctionPointer(Mock.data_load_reports_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void data_load_reports_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cJSON* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_data_load_reports_CALL_INSTANCE));
  CMOCK_data_load_reports_CALL_INSTANCE* cmock_call_instance = (CMOCK_data_load_reports_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.data_load_reports_CallInstance = CMock_Guts_MemChain(Mock.data_load_reports_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void data_load_reports_AddCallback(CMOCK_data_load_reports_CALLBACK Callback)
{
  Mock.data_load_reports_CallbackBool = (char)1;
  Mock.data_load_reports_CallbackFunctionPointer = Callback;
}

void data_load_reports_Stub(CMOCK_data_load_reports_CALLBACK Callback)
{
  Mock.data_load_reports_CallbackBool = (char)0;
  Mock.data_load_reports_CallbackFunctionPointer = Callback;
}

