/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDATA_H
#define _MOCKDATA_H

#include "unity.h"
#include "data.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockdata_Init(void);
void Mockdata_Destroy(void);
void Mockdata_Verify(void);




#define data_save_report_ExpectAnyArgs() TEST_FAIL_MESSAGE("data_save_report requires _ExpectAnyArgsAndReturn");
#define data_save_report_ExpectAnyArgsAndReturn(cmock_retval) data_save_report_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void data_save_report_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define data_save_report_Expect(report) TEST_FAIL_MESSAGE("data_save_report requires _ExpectAndReturn");
#define data_save_report_ExpectAndReturn(report, cmock_retval) data_save_report_CMockExpectAndReturn(__LINE__, report, cmock_retval)
void data_save_report_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cJSON* report, int cmock_to_return);
typedef int (* CMOCK_data_save_report_CALLBACK)(cJSON* report, int cmock_num_calls);
void data_save_report_AddCallback(CMOCK_data_save_report_CALLBACK Callback);
void data_save_report_Stub(CMOCK_data_save_report_CALLBACK Callback);
#define data_save_report_StubWithCallback data_save_report_Stub
#define data_load_reports_Expect() TEST_FAIL_MESSAGE("data_load_reports requires _ExpectAndReturn");
#define data_load_reports_ExpectAndReturn(cmock_retval) data_load_reports_CMockExpectAndReturn(__LINE__, cmock_retval)
void data_load_reports_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cJSON* cmock_to_return);
typedef cJSON* (* CMOCK_data_load_reports_CALLBACK)(int cmock_num_calls);
void data_load_reports_AddCallback(CMOCK_data_load_reports_CALLBACK Callback);
void data_load_reports_Stub(CMOCK_data_load_reports_CALLBACK Callback);
#define data_load_reports_StubWithCallback data_load_reports_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
