/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockrun.h"

static const char* CMockString_run = "run";

typedef struct _CMOCK_run_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;

} CMOCK_run_CALL_INSTANCE;

static struct MockrunInstance
{
  char run_CallbackBool;
  CMOCK_run_CALLBACK run_CallbackFunctionPointer;
  int run_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE run_CallInstance;
} Mock;


void Mockrun_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.run_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_run);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.run_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockrun_Init(void)
{
  Mockrun_Destroy();
}

void Mockrun_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int run(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_run_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_run);
  cmock_call_instance = (CMOCK_run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.run_CallInstance);
  Mock.run_CallInstance = CMock_Guts_MemNext(Mock.run_CallInstance);
  if (!Mock.run_CallbackBool &&
      Mock.run_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.run_CallbackFunctionPointer(Mock.run_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.run_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.run_CallbackFunctionPointer(Mock.run_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void run_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_run_CALL_INSTANCE));
  CMOCK_run_CALL_INSTANCE* cmock_call_instance = (CMOCK_run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.run_CallInstance = CMock_Guts_MemChain(Mock.run_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void run_AddCallback(CMOCK_run_CALLBACK Callback)
{
  Mock.run_CallbackBool = (char)1;
  Mock.run_CallbackFunctionPointer = Callback;
}

void run_Stub(CMOCK_run_CALLBACK Callback)
{
  Mock.run_CallbackBool = (char)0;
  Mock.run_CallbackFunctionPointer = Callback;
}

