/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockpresentation.h"

static const char* CMockString_presentation_collect_and_save_report = "presentation_collect_and_save_report";

typedef struct _CMOCK_presentation_collect_and_save_report_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_presentation_collect_and_save_report_CALL_INSTANCE;

static struct MockpresentationInstance
{
  char presentation_collect_and_save_report_CallbackBool;
  CMOCK_presentation_collect_and_save_report_CALLBACK presentation_collect_and_save_report_CallbackFunctionPointer;
  int presentation_collect_and_save_report_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE presentation_collect_and_save_report_CallInstance;
} Mock;


void Mockpresentation_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.presentation_collect_and_save_report_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_presentation_collect_and_save_report);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.presentation_collect_and_save_report_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockpresentation_Init(void)
{
  Mockpresentation_Destroy();
}

void Mockpresentation_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void presentation_collect_and_save_report(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_presentation_collect_and_save_report_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_presentation_collect_and_save_report);
  cmock_call_instance = (CMOCK_presentation_collect_and_save_report_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.presentation_collect_and_save_report_CallInstance);
  Mock.presentation_collect_and_save_report_CallInstance = CMock_Guts_MemNext(Mock.presentation_collect_and_save_report_CallInstance);
  if (!Mock.presentation_collect_and_save_report_CallbackBool &&
      Mock.presentation_collect_and_save_report_CallbackFunctionPointer != NULL)
  {
    Mock.presentation_collect_and_save_report_CallbackFunctionPointer(Mock.presentation_collect_and_save_report_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.presentation_collect_and_save_report_CallbackFunctionPointer != NULL)
  {
    Mock.presentation_collect_and_save_report_CallbackFunctionPointer(Mock.presentation_collect_and_save_report_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void presentation_collect_and_save_report_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_presentation_collect_and_save_report_CALL_INSTANCE));
  CMOCK_presentation_collect_and_save_report_CALL_INSTANCE* cmock_call_instance = (CMOCK_presentation_collect_and_save_report_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.presentation_collect_and_save_report_CallInstance = CMock_Guts_MemChain(Mock.presentation_collect_and_save_report_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void presentation_collect_and_save_report_AddCallback(CMOCK_presentation_collect_and_save_report_CALLBACK Callback)
{
  Mock.presentation_collect_and_save_report_CallbackBool = (char)1;
  Mock.presentation_collect_and_save_report_CallbackFunctionPointer = Callback;
}

void presentation_collect_and_save_report_Stub(CMOCK_presentation_collect_and_save_report_CALLBACK Callback)
{
  Mock.presentation_collect_and_save_report_CallbackBool = (char)0;
  Mock.presentation_collect_and_save_report_CallbackFunctionPointer = Callback;
}

