/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKRUN_H
#define _MOCKRUN_H

#include "unity.h"
#include "run.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockrun_Init(void);
void Mockrun_Destroy(void);
void Mockrun_Verify(void);




#define run_Expect() TEST_FAIL_MESSAGE("run requires _ExpectAndReturn");
#define run_ExpectAndReturn(cmock_retval) run_CMockExpectAndReturn(__LINE__, cmock_retval)
void run_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
typedef int (* CMOCK_run_CALLBACK)(int cmock_num_calls);
void run_AddCallback(CMOCK_run_CALLBACK Callback);
void run_Stub(CMOCK_run_CALLBACK Callback);
#define run_StubWithCallback run_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
